export default {
    urlEndpoint: "https://ik.imagekit.io/showimg/restorant-tutto-rico",
    logoNav: "tuttoLogo_po2GkzOEi.svg",
    footer: {
        igLogo: "igLogo_mT0wf2210.svg",
        fbLogo: "fbLogo_Zsy73e_uh.svg",
        twLogo: "twLogo_dd2mvuyUf.svg"
    }
    ,
    config: {
        individial: false,
        grupos: [
            { nombre: "empanadas", oculto: false, orden: [1, 2, 3] },
            { nombre: "pizzas", oculto: false, orden: [1, 2, 3, 4] },
            { nombre: "postres", oculto: false, orden: [1, 2, 3, 4] },
            { nombre: "pastas", oculto: false, orden: [1, 2] },
            { nombre: "tartas", oculto: false, orden: [1, 2] },
            { nombre: "sanguches", oculto: false, orden: [1, 2] }
        ]
    },
    comidas: [
        {
            grupo: "empanadas",
            idGroup: 1,
            nombre: "empanada de pollo",
            url: "emp-3_ibCNm4baT.jpg",
            descr: "Empanada con masa de hojaldre recien cosinada",
            precio: 50,
        },
        {
            grupo: "empanadas",
            idGroup: 2,
            nombre: "empanada de carne",
            url: "emp-1_yzByGAPpv.jpg",
            descr: "Empanada con masa de hojaldre recien cosinada",
            precio: 50,
        },
        {
            grupo: "empanadas",
            idGroup: 3,
            nombre: "empanada de Jamon y Queso",
            url: "empanada-jamonyQueso_0sioOflRu.jpg",
            descr: "Empanada con masa de hojaldre recien cosinada",
            precio: 50,
        },
        {
            grupo: "pizzas",
            idGroup: 1,
            nombre: "Pizza Muzzarella",
            url: "pizza-5_CRTeh-p3P.jpg",
            descr: "Pizza de horno de barro con muzzarella",
            precio: 800,
        },
        {
            grupo: "pizzas",
            idGroup: 2,
            nombre: "Pizza Espesial",
            url: "pizza-4_xmAUzmtcK.jpg",
            descr: "Pizza de horno de barro con muzzarella, jamon y morron",
            precio: 1000,
        },
        {
            grupo: "pizzas",
            idGroup: 3,
            nombre: "Pizza comun",
            url: "pizza-3_Bxbm-OBGr.webp",
            descr: "Pizza de horno de barro",
            precio: 700,
        },
        {
            grupo: "pizzas",
            idGroup: 4,
            nombre: "Pizza Calabresa",
            url: "pizza-2_4xX4ZcqEBN.jpg",
            descr: "Pizza de horno de barro con Calabresa",
            precio: 850,
        },
        {
            grupo: "postres",
            idGroup: 1,
            nombre: "Flan",
            url: "postre-2_2GZxwSn3f.jpg",
            descr: "postre frio elaborado con una natilla, con ingredientes principales huevos enteros, leche y azúcar,",
            precio: 400,
        },
        {
            grupo: "postres",
            idGroup: 2,
            nombre: "Budin de Pan",
            url: "postre-1_ZWK6jjpWZ.webp",
            descr: "postre frio elaborado con pan, con ingredientes principales huevos enteros, leche y azúcar",
            precio: 400,
        },
        {
            grupo: "postres",
            idGroup: 3,
            nombre: "Helado",
            url: "postre-4_onpUG9wCa.jpg",
            descr: "postre fresco hecho con leche",
            precio: 400,
        },
        {
            grupo: "postres",
            idGroup: 4,
            nombre: "Tarta Cabsha",
            url: "postre-5_E4TeuR_Lu.jpg",
            descr: "Tarta con cobertura de chocolate y relleno de dulce de leche",
            precio: 400,
        },
        {
            grupo: "pastas",
            idGroup: 1,
            nombre: "Spageti",
            url: "past-4_q_DzGi-xI.jpg",
            descr: "Fideos spageti",
            precio: 800,
        },
        {
            grupo: "pastas",
            idGroup: 2,
            nombre: "Ravioles",
            url: "past-3__neIQ-4S2.jpg",
            descr: "ravioles rellenos de queso",
            precio: 700,
        },
        {
            grupo: "tartas",
            idGroup: 1,
            nombre: "Tarta de Espinaca",
            url: "tarta-1_SdFbIIWYm.jpg",
            descr: "tarta con masa de hojaldre y relleno de espinaca",
            precio: 800,
        },
        {
            grupo: "tartas",
            idGroup: 2,
            nombre: "Tarta Primavera",
            url: "tarta-3_Hucq2XqLN.png",
            descr: "tarta con masa de hojaldre y relleno con zanahoria,espinaca,choclo,jamon,y queso",
            precio: 850,
        },
        {
            grupo: "sanguches",
            idGroup: 1,
            nombre: "Sanguche de Milanesa",
            url: "sanguche-1_TrC7eZx8f.png",
            descr: "sanguche de carne de baca con pan recien horneado",
            precio: 700,
        },
        {
            grupo: "sanguches",
            idGroup: 2,
            nombre: "Sanguche de Pollo",
            url: "sanguche-2_Lt_j7dyKD.jpeg",
            descr: "sanguche de carne de pollo con pan recien horneado",
            precio: 700,
        }
    ]
}