const grupos = {
    g1: "Empanadas",
    g2: "Pizzas",
    g3: "Postres",
    g4: "Pastas",
    g5: "Tartas",
    g6: "Sanguches"
}

export default {
    urlEndpoint: "https://ik.imagekit.io/showimg/restorant-tutto-rico",
    catering:"salones-para-eventos_ukVLX31Sc.jpg",
    logoNav: "tuttoLogo_po2GkzOEi.svg",
    footer: {
        igLogo: "ig_-F5w84Q0O.svg",
        fbLogo: "fbLogo_Zsy73e_uh.svg",
        twLogo: "twLogo_dd2mvuyUf.svg"
    },
    portada: [
        "portada1_W-CNW0LKg.jpg",
        "portada2_9RztSDO_k.jpg",
        "portada3_yCNlRFIoz.webp",
    ],
    grupos,
    comidas: [
        {
            grupo: grupos.g1,
            idGroup: 1,
            nombre: "empanada de pollo",
            url: "emp-3_ibCNm4baT.jpg",
            descr: "Empanada con masa de hojaldre recien cosinada",
            precio: 50,
        },
        {
            grupo: grupos.g1,
            idGroup: 2,
            nombre: "empanada de carne",
            url: "emp-1_yzByGAPpv.jpg",
            descr: "Empanada con masa de hojaldre recien cosinada",
            precio: 50,
        },
        {
            grupo: grupos.g1,
            idGroup: 3,
            nombre: "empanada de Jamon y Queso",
            url: "empanada-jamonyQueso_0sioOflRu.jpg",
            descr: "Empanada con masa de hojaldre recien cosinada",
            precio: 50,
        },
        {
            grupo: grupos.g2,
            idGroup: 1,
            nombre: "Pizza Muzzarella",
            url: "pizza-5_CRTeh-p3P.jpg",
            descr: "Pizza de horno de barro con muzzarella",
            precio: 800,
        },
        {
            grupo: grupos.g2,
            idGroup: 2,
            nombre: "Pizza Espesial",
            url: "pizza-4_xmAUzmtcK.jpg",
            descr: "Pizza de horno de barro con muzzarella, jamon y morron",
            precio: 1000,
        },
        {
            grupo: grupos.g2,
            idGroup: 3,
            nombre: "Pizza comun",
            url: "pizza-3_Bxbm-OBGr.webp",
            descr: "Pizza de horno de barro",
            precio: 700,
        },
        {
            grupo: grupos.g2,
            idGroup: 4,
            nombre: "Pizza Calabresa",
            url: "pizza-2_4xX4ZcqEBN.jpg",
            descr: "Pizza de horno de barro con Calabresa",
            precio: 850,
        },
        {
            grupo: grupos.g3,
            idGroup: 1,
            nombre: "Flan",
            url: "postre-2_2GZxwSn3f.jpg",
            descr: "postre frio elaborado con una natilla, con ingredientes principales huevos enteros, leche y azúcar,",
            precio: 400,
        },
        {
            grupo: grupos.g3,
            idGroup: 2,
            nombre: "Budin de Pan",
            url: "postre-1_ZWK6jjpWZ.webp",
            descr: "postre frio elaborado con pan, con ingredientes principales huevos enteros, leche y azúcar",
            precio: 400,
        },
        {
            grupo: grupos.g3,
            idGroup: 3,
            nombre: "Helado",
            url: "postre-4_onpUG9wCa.jpg",
            descr: "postre fresco hecho con leche",
            precio: 400,
        },
        {
            grupo: grupos.g3,
            idGroup: 4,
            nombre: "Tarta Cabsha",
            url: "postre-5_E4TeuR_Lu.jpg",
            descr: "Tarta con cobertura de chocolate y relleno de dulce de leche",
            precio: 400,
        },
        {
            grupo: grupos.g4,
            idGroup: 1,
            nombre: "Spageti",
            url: "past-4_q_DzGi-xI.jpg",
            descr: "Fideos spageti",
            precio: 800,
        },
        {
            grupo: grupos.g4,
            idGroup: 2,
            nombre: "Ravioles",
            url: "past-3__neIQ-4S2.jpg",
            descr: "ravioles rellenos de queso",
            precio: 700,
        },
        {
            grupo: grupos.g5,
            idGroup: 1,
            nombre: "Tarta de Espinaca",
            url: "tarta-1_SdFbIIWYm.jpg",
            descr: "tarta con masa de hojaldre y relleno de espinaca",
            precio: 800,
        },
        {
            grupo: grupos.g5,
            idGroup: 2,
            nombre: "Tarta Primavera",
            url: "tarta-3_Hucq2XqLN.png",
            descr: "tarta con masa de hojaldre y relleno con zanahoria,espinaca,choclo,jamon,y queso",
            precio: 850,
        },
        {
            grupo: grupos.g6,
            idGroup: 1,
            nombre: "Sanguche de Milanesa",
            url: "sanguche-1_TrC7eZx8f.png",
            descr: "sanguche de carne de baca con pan recien horneado",
            precio: 700,
        },
        {
            grupo: grupos.g6,
            idGroup: 2,
            nombre: "Sanguche de Pollo",
            url: "sanguche-2_Lt_j7dyKD.jpeg",
            descr: "sanguche de carne de pollo con pan recien horneado",
            precio: 700,
        }
    ]
}